import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import "./globals.css";


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <body>
        <header className="border-b bg-background/70 backdrop-blur supports-[backdrop-filter]:bg-background/50">
          <div className="max-w-6xl mx-auto px-4 h-14 flex items-center justify-between">
            <Link href="/" className="font-semibold">KCC Mita</Link>
            <nav className="flex items-center gap-3">
              <Link href="/menu" className="text-sm opacity-80 hover:opacity-100">メニュー</Link>
              <Button asChild size="sm">
                <Link href="/quiz">診断する ☕</Link>
              </Button>
            </nav>
          </div>
        </header>
        <main className="min-h-[calc(100dvh-3.5rem)]">{children}</main>
      </body>
    </html>
  );
}

